// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Playercard struct {
	Name         string
	Age          sql.NullInt16
	Birthday     sql.NullTime
	Country      sql.NullString
	Team         sql.NullString
	Position     sql.NullString
	WorldsTitles sql.NullInt16
}
